# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.

def fib(number)
  fib_num = [1]
  last_num = 1
  even_num = []
  (1..number).each do |num|
    while fib_num.last < number do
      fib_num << last_num
      last_num = fib_num[-1] + fib_num[-2]
    end
  end
  fib_num.delete fib_num.last 
  fib_num.each do |num|
    if num % 2 ==0
      even_num << num
    end
  end
  return even_num.inject { |sum, value| sum += value } 
end